title: Hello, world! I'm Aslan Bakirov
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Aslan Bakirov # add your name
author-img: headshot.jpeg # add your photo
about-author: I am a software engineer interested in Machine Learning, ML Hardware (ASICs), Computational Neuroscience # add description
social-twitter: abekir# add your Twitter handle
social-github: aslanbakirov # add your Github handle
social-linkedin: aslanbakirov# add your Linkedin handle

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
